dependencies {
    compileOnly project(':bedwars-api')
    implementation project(':versionsupport_common')
    compileOnly 'org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT'
}

tasks.named('compileJava', JavaCompile) {
    options.release = 11
}

repositories {
    // Important Repos
    mavenCentral()
    mavenLocal()
    maven { url = uri('https://repo.codemc.io/repository/nms/') } // Spigot
}

description = 'versionsupport_v1_8_r3'
