dependencies {
    compileOnly project(':bedwars-api')
    api 'com.flowpowered:flow-nbt:2.0.2'
    compileOnly('org.spigotmc:spigot-api:1.21-R0.1-SNAPSHOT') {
        exclude group: 'commons-lang', module: 'commons-lang'
    }
    compileOnly 'com.infernalsuite.asp:api:4.0.0'
    implementation 'com.infernalsuite.asp:file-loader:4.0.0'
    compileOnly 'org.jetbrains:annotations:26.0.2'
    compileOnly 'commons-io:commons-io:2.11.0'
}

// Target Java 21 bytecode for this module
tasks.named('compileJava', JavaCompile) {
    options.release = 21
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/') } // Spigot
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') } // bungeecord-chat (dep of spigot-api)
    maven { url = uri('https://repo.infernalsuite.com/repository/maven-releases/') } // ASP:api
}
