dependencies {
    compileOnly project(':bedwars-api')
    api 'com.flowpowered:flow-nbt:2.0.2'
    compileOnly('org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT') {
        exclude group: 'commons-lang', module: 'commons-lang'
    }
    compileOnly 'com.infernalsuite.aswm:api:1.20-R0.1-SNAPSHOT'
    compileOnly 'commons-io:commons-io:2.11.0'
}

tasks.named('compileJava', JavaCompile) {
    options.release = 17
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = uri('https://repo.codemc.io/repository/nms/') } // Spigot
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') } // bungeecord-chat (dep of spigot-api)
    maven { url = uri('https://repo.infernalsuite.com/repository/maven-snapshots/') } // ASWM:api
}
